from flask import Flask, render_template, jsonify
import json
import os
import requests
import time

app = Flask(__name__)

# Config
# Railway will provide these via Env Vars, or secrets_config locally
API_KEY = None
TELEGRAM_BOT_TOKEN = None
TELEGRAM_CHAT_ID = None

try:
    from secrets_config import API_KEY as LOC_KEY, TELEGRAM_BOT_TOKEN as LOC_TOK, TELEGRAM_CHAT_ID as LOC_ID
    API_KEY = LOC_KEY
    TELEGRAM_BOT_TOKEN = LOC_TOK
    TELEGRAM_CHAT_ID = LOC_ID
except ImportError:
    pass

if not TELEGRAM_BOT_TOKEN:
    TELEGRAM_BOT_TOKEN = os.environ.get("TELEGRAM_BOT_TOKEN")
if not TELEGRAM_CHAT_ID:
    TELEGRAM_CHAT_ID = os.environ.get("TELEGRAM_CHAT_ID")

DASHBOARD_FILE = "dashboard_data.json"

def send_telegram_message(message):
    try:
        if not TELEGRAM_BOT_TOKEN or not TELEGRAM_CHAT_ID:
            print("Telegram keys missing")
            return False
        url = f"https://api.telegram.org/bot{TELEGRAM_BOT_TOKEN}/sendMessage"
        payload = {"chat_id": TELEGRAM_CHAT_ID, "text": message}
        requests.post(url, json=payload, timeout=5)
        return True
    except Exception as e:
        print(f"Telegram Err: {e}")
        return False

@app.route('/')
def index():
    return render_template('index.html')

@app.route('/data')
def get_data():
    """Serve the latest data generated by tracker.py"""
    if os.path.exists(DASHBOARD_FILE):
        try:
            with open(DASHBOARD_FILE, 'r') as f:
                data = json.load(f)
                return jsonify(data)
        except Exception as e:
            return jsonify({"error": f"Error reading data: {e}"})
    else:
        return jsonify({"error": "Waiting for tracker to generate data..."})

@app.route('/send_telegram', methods=['POST'])
def trigger_manual_telegram():
    if os.path.exists(DASHBOARD_FILE):
        try:
            with open(DASHBOARD_FILE, 'r') as f:
                data = json.load(f)
            
            lines = ["📊 *Manual NAV Update*"]
            lines.append(f"_{data.get('last_updated', '?')}_")
            lines.append("")
            for cef in data.get('cefs', []):
                icon = "➖"
                move = cef.get('implied_move', 0.0)
                if move > 0: icon = "🟢"
                if move < 0: icon = "🔴"
                lines.append(f"{icon} *{cef['name']}*: {move:+.3f}%")
            
            message = "\n".join(lines)
            if send_telegram_message(message):
                return jsonify({"success": True})
            else:
                return jsonify({"success": False, "message": "Failed to send to Telegram API"})
        except Exception as e:
            return jsonify({"success": False, "message": str(e)})
    
    return jsonify({"success": False, "message": "No data available yet"})

if __name__ == '__main__':
    # Railway passes PORT, default to 5000
    port = int(os.environ.get("PORT", 5000))
    app.run(host='0.0.0.0', port=port)
